# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TuesQuestionnaireApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='multiple_answers',
        ),
    ]
