# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuesQuestionnaireApp', '0002_remove_question_multiple_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('questions', models.ManyToManyField(to='TuesQuestionnaireApp.Question')),
            ],
        ),
    ]
