# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TuesQuestionnaireApp', '0004_auto_20170108_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
