# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TuesQuestionnaireApp', '0011_auto_20170110_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='TuesQuestionnaireApp.Attempt'),
        ),
    ]
