# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuesQuestionnaireApp', '0012_auto_20170112_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allowed_attempts',
            field=models.IntegerField(default=1),
        ),
    ]
